org.gradle.caching=true
group=io.ballerina.stdlib
version=2.14.1-SNAPSHOT

// Java Dependencies
slf4jVersion=1.7.30
testngVersion=7.6.1
javaMailVersion=1.6.2
greenmailVersion=1.6.15
mimepullVersion=1.9.11
javaxActivationVersion=1.1.1
bouncycastleVersion=1.80
jacksonDatabindVersion=2.17.2

// Gradle Plugins
checkstylePluginVersion=10.12.0
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
ballerinaGradlePluginVersion=4.0.0

ballerinaLangVersion=2201.14.0-20260527-050400-74f7e6bf
stdlibTaskVersion=2.11.1
stdlibMimeVersion=2.12.1
stdlibFileVersion=1.12.0
stdlibTimeVersion=2.7.0
stdlibLogVersion=2.12.0
stdlibOsVersion=1.10.1
stdlibIoVersion=1.8.0
observeVersion=1.5.1
observeInternalVersion=1.5.0

stdlibOAuth2Version=2.14.1

balScanVersion=0.11.0
jacocoVersion=0.8.13
